AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an aws custom config rule that checks glue crawlers enforce ssl for their connections

Parameters:
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket where the Lambda Code is uploaded as a Zip file

  S3KeyPrefixComplianceCheck:
    Type: String
    Description: S3 prefix path for Compliance Check Lambda function including the Zip file name
    Default: Lambdas/config_rule_glue_crawler_enforce_connection_ssl.py.zip

  S3KeyPrefixRemediation:
    Type: String
    Description: S3 prefix path for remediation Lambda function including the Zip file name
    Default: Lambdas/remediate_connection_ssl.py.zip
  
Resources:
  GlueLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: Description
          Value: !Sub Lambda role for compliance check - ${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: Enfore_Glue_Crawler_Connection_SSL_Config_Rule_Permission
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: logs:*
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
              - config:PutEvaluations
              - config:GetComplianceDetailsByConfigRule
              - glue:GetCrawler
              - glue:GetCrawlers
              - glue:UpdateCrawler
              - glue:GetConnections
              - glue:GetConnection
              - glue:CreateConnection
              - glue:UpdateConnection
              - iam:PassRole
              - kms:Encrypt
              - kms:Decrypt
              - kms:GenerateDataKey
              - kms:DescribeKey
            Resource: '*'
  
  GlueCrawlerSSLComplianceCheck:
    Type: AWS::Lambda::Function
    Properties:
      Description: Function to check compliance with GlueCrawlerSSLConfigRule
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3KeyPrefixComplianceCheck
      FunctionName: GlueCrawlerSSL_ComplianceCheck
      Role: !GetAtt GlueLambdaExecutionRole.Arn
      Runtime: python3.8
      Handler: config_rule_glue_crawler_enforce_connection_ssl.lambda_handler
      Timeout: 15 #seconds

  ConfigPermissionToCallLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt GlueCrawlerSSLComplianceCheck.Arn
      Action: "lambda:InvokeFunction"
      Principal: "config.amazonaws.com"
      SourceAccount: !Ref 'AWS::AccountId'

  GlueCrawlerSSLConfigRule:
    Type: AWS::Config::ConfigRule
    Properties:
      Description: This rule checks whether glue crawle to MongoDb and JDBC enfore SSL
      ConfigRuleName: Enfore_Glue_Crawler_Connection_Via_SSL
      MaximumExecutionFrequency: TwentyFour_Hours #Allowed values: One_Hour | Six_Hours | Three_Hours | Twelve_Hours | TwentyFour_Hours
      Source:
        Owner: "CUSTOM_LAMBDA"
        SourceDetails:
          - EventSource: "aws.config"
            MessageType: "ConfigurationItemChangeNotification"
        SourceIdentifier: !GetAtt GlueCrawlerSSLComplianceCheck.Arn
    DependsOn: ConfigPermissionToCallLambda

  GlueCrawlerSSLRemediation:
    Type: AWS::Lambda::Function
    Properties:
      Description: Function to remediate GlueCrawlerSSL ConfigRule
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3KeyPrefixRemediation
      FunctionName: GlueCrawlerSSL_Remediation
      Role: !GetAtt GlueLambdaExecutionRole.Arn
      Runtime: python3.8
      Handler: remediate_connection_ssl.lambda_handler
      Timeout: 15 #seconds

  RemediationSSMDoc:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Automation  
      Content:
        description: This document invokes the remdiation function to enfore SSL on a Glue connection
        schemaVersion: '0.3' #automation documents use this version
        parameters: 
          ResourceId:
            type: String
            description: Name of non compliant resource
        mainSteps:
        - name: invokeRemediationFunction
          action: aws:invokeLambdaFunction
          maxAttempts: 3 
          timeoutSeconds: 60
          onFailure: Abort
          inputs:
            FunctionName: !Ref GlueCrawlerSSLRemediation
            Payload: |-
              {
                "ResourceId": "{{ ResourceId }}"
              }
      
  GlueCrawlerSSLRemediationConfiguration:
    Type: AWS::Config::RemediationConfiguration
    Properties: 
      Automatic: False
      ConfigRuleName: !Ref GlueCrawlerSSLConfigRule
      Parameters:
        ResourceId:
          ResourceValue:
            Value: "RESOURCE_ID"
      TargetId: !Ref RemediationSSMDoc
      TargetType: "SSM_DOCUMENT"
    DependsOn: GlueCrawlerSSLRemediation

Outputs:
  RemediationLambda: 
    Value: !Ref GlueCrawlerSSLRemediation
  ComplianceCheckLambda:
    Value: !Ref GlueCrawlerSSLComplianceCheck
  RemediationSSMDoc:
    Value: !Ref RemediationSSMDoc